### PR TITLE
Updating the inputRules branch

### PR DESCRIPTION
**Pull request by Devlan-Mckenzie**
-Pulling the commits from main into inputRules

### CODE REVIEW

**Comment by Muchaveleli** [comment]
Is this not the bugged branch?

**Comment by Muchaveleli** [comment]
What exactly are you trying to do and why?

**Comment by Devlan-Mckenzie** [comment]
Just updating the branch with the code from main

**Comment by Devlan-Mckenzie** [comment]
I am doing this because this branch has outdated git ignore files and such so I want to updated them

**Pull request merged**
